/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author MARCEL
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu(String usuario, String storage) {
        initComponents();
        setLocationRelativeTo(null);
        
        lblUsuario.setText(usuario);
        lblAlmacen.setText(storage);
    }

    public Menu() {
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRequerimiento = new javax.swing.JButton();
        btnTraslado = new javax.swing.JButton();
        btnCierreBarman = new javax.swing.JButton();
        btnRecetas = new javax.swing.JButton();
        btnRequerimiento1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblAlmacen = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        txtHora = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MENU BARMAN");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRequerimiento.setBackground(new java.awt.Color(0, 153, 255));
        btnRequerimiento.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnRequerimiento.setForeground(new java.awt.Color(255, 255, 255));
        btnRequerimiento.setText("REQUERIMIENTOS");
        btnRequerimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequerimientoActionPerformed(evt);
            }
        });
        getContentPane().add(btnRequerimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 180, 40));

        btnTraslado.setBackground(new java.awt.Color(0, 153, 255));
        btnTraslado.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnTraslado.setForeground(new java.awt.Color(255, 255, 255));
        btnTraslado.setText("TRASLADOS");
        btnTraslado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrasladoActionPerformed(evt);
            }
        });
        getContentPane().add(btnTraslado, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 180, 40));

        btnCierreBarman.setBackground(new java.awt.Color(0, 153, 255));
        btnCierreBarman.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnCierreBarman.setForeground(new java.awt.Color(255, 255, 255));
        btnCierreBarman.setText("CIERRE BARMAN");
        btnCierreBarman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCierreBarmanActionPerformed(evt);
            }
        });
        getContentPane().add(btnCierreBarman, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 180, 40));

        btnRecetas.setBackground(new java.awt.Color(0, 153, 255));
        btnRecetas.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnRecetas.setForeground(new java.awt.Color(255, 255, 255));
        btnRecetas.setText("RECETAS");
        btnRecetas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecetasActionPerformed(evt);
            }
        });
        getContentPane().add(btnRecetas, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 180, 40));

        btnRequerimiento1.setBackground(new java.awt.Color(0, 153, 255));
        btnRequerimiento1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnRequerimiento1.setForeground(new java.awt.Color(255, 255, 255));
        btnRequerimiento1.setText("APERTURA BARMAN");
        btnRequerimiento1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequerimiento1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnRequerimiento1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 180, 40));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("USUARIO:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, -1));

        lblUsuario.setText("...");
        jPanel1.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 130, -1));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("AREA:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 60, -1));

        lblAlmacen.setText("...");
        jPanel1.add(lblAlmacen, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 130, -1));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("FECHA:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 60, -1));

        lblFecha.setText("...");
        jPanel1.add(lblFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 110, -1));
        jPanel1.add(txtHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 110, -1));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("HORA");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 60, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 420, 60));

        jButton1.setText("CERRAR SESION");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRequerimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequerimientoActionPerformed
        try {
            VistaRequerimientoBarman req = new VistaRequerimientoBarman(lblUsuario.getText(), lblAlmacen.getText());
            req.setVisible(true);
            dispose();
        } catch (Exception ex) {
        }
    }//GEN-LAST:event_btnRequerimientoActionPerformed

    private void btnTrasladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrasladoActionPerformed
        try {
            MovimientosBarras mb = new MovimientosBarras(lblUsuario.getText(), lblAlmacen.getText());
            mb.setVisible(true);
            dispose();
        } catch (Exception ex) {
            System.out.println("Error: "+ex.getMessage());
        }
    }//GEN-LAST:event_btnTrasladoActionPerformed

    private void btnCierreBarmanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCierreBarmanActionPerformed
        try {
            CierreBarman ii = new CierreBarman(lblUsuario.getText(), lblAlmacen.getText());
            ii.setVisible(true);
            dispose();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnCierreBarmanActionPerformed

    private void btnRecetasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecetasActionPerformed
        try {
            Recetas ii = new Recetas(lblUsuario.getText(), lblAlmacen.getText());
            ii.setVisible(true);
            dispose();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnRecetasActionPerformed

    private void btnRequerimiento1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequerimiento1ActionPerformed
        try {
            InventarioInicial ii = new InventarioInicial(lblUsuario.getText(), lblAlmacen.getText());
            ii.setVisible(true);
            dispose();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnRequerimiento1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Login l = new Login();
        l.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCierreBarman;
    private javax.swing.JButton btnRecetas;
    private javax.swing.JButton btnRequerimiento;
    private javax.swing.JButton btnRequerimiento1;
    private javax.swing.JButton btnTraslado;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAlmacen;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JTextField txtHora;
    // End of variables declaration//GEN-END:variables
}
