
package Vista;

import Controlador.ColumnasTablas;
import Controlador.Cronometro;
import Controlador.ManejadorFechas;
import Modelo.MySQLDAO.Conexion;
import Modelo.MySQLDAO.PreparacionDAO;
import Modelo.MySQLDAO.ProductoPresentacionDAO;
import Modelo.ProductoPresentacion;
import Modelo.Preparacion;
import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MARCEL
 */
public class Recetas extends javax.swing.JFrame {

    DefaultTableModel modeloBuscarProductos;
    DefaultTableModel modeloBuscarProductoPresentacion;
    DefaultTableModel modeloPreparaciones;
    String usuario;

    public Recetas(String user, String storage) {
        initComponents();        
        setLocationRelativeTo(null);
        
        this.usuario = user;
        
        lblUsuario.setText(usuario);
        lblAlmacen.setText(storage);
        lblFecha.setText(new ManejadorFechas().getFechaActual());
        new Cronometro().iniciarCronometro(txtHora);
        
        titulosPreparaciones();
    }

    public Recetas() {
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelProductos = new javax.swing.JDialog();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblBuscarProductos = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtFiltroProducto = new javax.swing.JTextField();
        btnSeleccionarProducto = new javax.swing.JButton();
        panelProductoPresentacion = new javax.swing.JDialog();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblBuscarProductoPresentacion = new javax.swing.JTable();
        jPanel9 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtFiltroProductoPresentacion = new javax.swing.JTextField();
        btnSeleccionarProductoPresentacion = new javax.swing.JButton();
        lblCodProducto = new javax.swing.JLabel();
        btnPreparar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblPreparacion = new javax.swing.JTable();
        txtCantidad = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        btnQuitar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        txtBebida = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        btnProductoBase = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        txtComponente = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblProductoPresentacion = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtHora = new javax.swing.JTextField();
        lblUsuario = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        lblAlmacen = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        tblBuscarProductos = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        tblBuscarProductos.setFont(new java.awt.Font("Microsoft Yi Baiti", 0, 18)); // NOI18N
        tblBuscarProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblBuscarProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBuscarProductosMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblBuscarProductos);

        panelProductos.getContentPane().add(jScrollPane4, java.awt.BorderLayout.CENTER);

        jPanel8.setBackground(new java.awt.Color(204, 204, 204));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Microsoft Yi Baiti", 0, 24)); // NOI18N
        jLabel8.setText("PRODUCTO");
        jPanel8.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 140, 30));

        txtFiltroProducto.setBackground(new java.awt.Color(204, 204, 204));
        txtFiltroProducto.setFont(new java.awt.Font("Microsoft Yi Baiti", 0, 24)); // NOI18N
        txtFiltroProducto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFiltroProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFiltroProductoKeyReleased(evt);
            }
        });
        jPanel8.add(txtFiltroProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 250, -1));

        panelProductos.getContentPane().add(jPanel8, java.awt.BorderLayout.NORTH);

        btnSeleccionarProducto.setBackground(new java.awt.Color(153, 255, 153));
        btnSeleccionarProducto.setFont(new java.awt.Font("Microsoft Yi Baiti", 0, 24)); // NOI18N
        btnSeleccionarProducto.setText("seleccionar");
        btnSeleccionarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarProductoActionPerformed(evt);
            }
        });
        panelProductos.getContentPane().add(btnSeleccionarProducto, java.awt.BorderLayout.PAGE_END);

        tblBuscarProductoPresentacion = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        tblBuscarProductoPresentacion.setFont(new java.awt.Font("Microsoft Yi Baiti", 0, 18)); // NOI18N
        tblBuscarProductoPresentacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblBuscarProductoPresentacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBuscarProductoPresentacionMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tblBuscarProductoPresentacion);

        panelProductoPresentacion.getContentPane().add(jScrollPane5, java.awt.BorderLayout.CENTER);

        jPanel9.setBackground(new java.awt.Color(204, 204, 204));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Microsoft Yi Baiti", 0, 24)); // NOI18N
        jLabel10.setText("PRODUCTO");
        jPanel9.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 140, 30));

        txtFiltroProductoPresentacion.setBackground(new java.awt.Color(204, 204, 204));
        txtFiltroProductoPresentacion.setFont(new java.awt.Font("Microsoft Yi Baiti", 0, 24)); // NOI18N
        txtFiltroProductoPresentacion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFiltroProductoPresentacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFiltroProductoPresentacionKeyReleased(evt);
            }
        });
        jPanel9.add(txtFiltroProductoPresentacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 250, -1));

        panelProductoPresentacion.getContentPane().add(jPanel9, java.awt.BorderLayout.NORTH);

        btnSeleccionarProductoPresentacion.setBackground(new java.awt.Color(153, 255, 153));
        btnSeleccionarProductoPresentacion.setFont(new java.awt.Font("Microsoft Yi Baiti", 0, 24)); // NOI18N
        btnSeleccionarProductoPresentacion.setText("seleccionar");
        btnSeleccionarProductoPresentacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarProductoPresentacionActionPerformed(evt);
            }
        });
        panelProductoPresentacion.getContentPane().add(btnSeleccionarProductoPresentacion, java.awt.BorderLayout.PAGE_END);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("RECETAS MR JUERGA");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCodProducto.setFont(new java.awt.Font("Microsoft Yi Baiti", 0, 14)); // NOI18N
        lblCodProducto.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(lblCodProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 80, 20));

        btnPreparar.setBackground(new java.awt.Color(0, 153, 0));
        btnPreparar.setFont(new java.awt.Font("Microsoft Yi Baiti", 0, 18)); // NOI18N
        btnPreparar.setForeground(new java.awt.Color(255, 255, 255));
        btnPreparar.setText("GUARDAR RECETA");
        btnPreparar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrepararActionPerformed(evt);
            }
        });
        getContentPane().add(btnPreparar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 700, 190, 30));

        tblPreparacion = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        tblPreparacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tblPreparacion);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 440, 220));

        txtCantidad.setFont(new java.awt.Font("Microsoft Yi Baiti", 0, 18)); // NOI18N
        txtCantidad.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 100, -1));

        btnAgregar.setBackground(new java.awt.Color(153, 255, 153));
        btnAgregar.setFont(new java.awt.Font("Microsoft Yi Baiti", 0, 18)); // NOI18N
        btnAgregar.setText("AGREGAR +");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 150, 40));

        btnQuitar.setBackground(new java.awt.Color(204, 0, 0));
        btnQuitar.setFont(new java.awt.Font("Microsoft Yi Baiti", 0, 18)); // NOI18N
        btnQuitar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_Trash_16px.png"))); // NOI18N
        btnQuitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitarActionPerformed(evt);
            }
        });
        getContentPane().add(btnQuitar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 680, 40, 30));

        btnBuscar.setFont(new java.awt.Font("Microsoft Yi Baiti", 0, 18)); // NOI18N
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/find.png"))); // NOI18N
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, 40, 30));

        txtBebida.setEditable(false);
        txtBebida.setFont(new java.awt.Font("Microsoft Yi Baiti", 0, 18)); // NOI18N
        getContentPane().add(txtBebida, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 400, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 440, 10));

        btnProductoBase.setFont(new java.awt.Font("Microsoft Yi Baiti", 0, 18)); // NOI18N
        btnProductoBase.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/find.png"))); // NOI18N
        btnProductoBase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductoBaseActionPerformed(evt);
            }
        });
        getContentPane().add(btnProductoBase, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 270, 40, 30));

        jLabel16.setFont(new java.awt.Font("Microsoft Yi Baiti", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 51, 51));
        jLabel16.setText("COMPONENTE");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        txtComponente.setEditable(false);
        txtComponente.setFont(new java.awt.Font("Microsoft Yi Baiti", 0, 18)); // NOI18N
        txtComponente.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txtComponente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 400, -1));

        jLabel7.setFont(new java.awt.Font("Microsoft Yi Baiti", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("CANTIDAD ML");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 110, -1));

        jLabel9.setFont(new java.awt.Font("Microsoft Yi Baiti", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("COD:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 30, -1));

        jLabel11.setFont(new java.awt.Font("Microsoft Yi Baiti", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("COD:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 30, -1));

        lblProductoPresentacion.setFont(new java.awt.Font("Microsoft Yi Baiti", 0, 14)); // NOI18N
        lblProductoPresentacion.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(lblProductoPresentacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 80, 20));

        btnVolver.setBackground(new java.awt.Color(102, 102, 102));
        btnVolver.setFont(new java.awt.Font("Microsoft Yi Baiti", 0, 18)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver.setText("VOLVER");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        getContentPane().add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 740, 190, 30));

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("RECETAS");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        txtHora.setEditable(false);
        txtHora.setBackground(new java.awt.Color(102, 102, 102));
        txtHora.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtHora.setForeground(new java.awt.Color(255, 255, 255));
        txtHora.setBorder(null);
        jPanel1.add(txtHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 170, -1));

        lblUsuario.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblUsuario.setText("....");
        jPanel1.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 180, -1));

        lblFecha.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblFecha.setForeground(new java.awt.Color(255, 255, 255));
        lblFecha.setText("....");
        jPanel1.add(lblFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, 170, -1));

        lblAlmacen.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblAlmacen.setForeground(new java.awt.Color(255, 255, 255));
        lblAlmacen.setText("....");
        jPanel1.add(lblAlmacen, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 170, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 130));

        jLabel12.setFont(new java.awt.Font("Microsoft Yi Baiti", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("NOMBRE DE PRODUCTO");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrepararActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrepararActionPerformed

        try {
            Preparacion p = new Preparacion();
            int c = 0;
            int idProducto = Integer.parseInt(lblCodProducto.getText());
            PreparacionDAO pdao = new PreparacionDAO();
            ProductoPresentacion pp = null;
            for (int i = 0; i < pdao.Listar(idProducto).size(); i++) {
                int idPreparacion = pdao.Listar().get(i).getIdPreparacion();
                pp = new ProductoPresentacionDAO().Obtener(tblPreparacion.getValueAt(i, 1).toString(), 1);
            }

            for (int i = 0; i < tblPreparacion.getRowCount(); i++) {
                p.setIdProducto(idProducto);
                p.setIdProductoPresentacion(Integer.parseInt(tblPreparacion.getValueAt(i, 0).toString()));
                p.setCantidad(Double.parseDouble(tblPreparacion.getValueAt(i, 2).toString()));
                p.setDetalles("");
                if (pdao.Registrar(p)) {
                    System.out.println("preparacion registrada");
                    c++;
                }
            }

            if (c > 0) {
                JOptionPane.showMessageDialog(getRootPane(), "SE REGISTRO LA RECETA");
                txtBebida.setText("");
                txtCantidad.setText("");
                txtComponente.setText("");
                lblCodProducto.setText("");
                lblProductoPresentacion.setText("");
                LimpiarTabla(tblPreparacion, modeloPreparaciones);
            }

        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btnPrepararActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        if (!txtBebida.getText().trim().isEmpty()) {
            if (!txtComponente.getText().trim().isEmpty()) {
                if (!txtCantidad.getText().trim().isEmpty()) {
                    String datos[] = new String[3];

                    datos[0] = lblProductoPresentacion.getText();
                    datos[1] = txtComponente.getText();
                    datos[2] = txtCantidad.getText();

                    modeloPreparaciones.addRow(datos);

                    tblPreparacion.setModel(modeloPreparaciones);

                    txtComponente.setText("");
                    lblProductoPresentacion.setText("");
                    txtCantidad.setText("");

                } else {
                    JOptionPane.showMessageDialog(getRootPane(), "INDIQUE LA MEDIDA DEL COMPONENTE");
                }
            } else {
                JOptionPane.showMessageDialog(getRootPane(), "AGREGE UN COMPONENTE");
            }
        } else {
            JOptionPane.showMessageDialog(getRootPane(), "DEBE INDICAR EL PRODUCTO PRINCIPAL");
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnQuitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitarActionPerformed
        int fila = tblPreparacion.getSelectedRow();

        if (fila >= 0) {
            modeloPreparaciones.removeRow(fila);
        } else {
            JOptionPane.showMessageDialog(getRootPane(), "SELECCIONE UN COMPONENTE");
        }
    }//GEN-LAST:event_btnQuitarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        panelProductos.setBounds(300, 300, 512, 560);
        panelProductos.setVisible(true);

        try {
            LlenarTablaBuscarProductos("");
        } catch (Exception ex) {
            Logger.getLogger(Recetas.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnProductoBaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductoBaseActionPerformed
        panelProductoPresentacion.setBounds(300, 300, 512, 560);
        panelProductoPresentacion.setVisible(true);

        try {
            LlenarTablaBuscarProductoPresentacion("");
        } catch (Exception ex) {
            Logger.getLogger(Recetas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnProductoBaseActionPerformed

    private void tblBuscarProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBuscarProductosMouseClicked
        if (evt.getClickCount() == 2) {
            btnSeleccionarProducto.doClick();
        }
    }//GEN-LAST:event_tblBuscarProductosMouseClicked

    private void txtFiltroProductoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFiltroProductoKeyReleased
        try {
            LlenarTablaBuscarProductos(txtFiltroProducto.getText());
        } catch (Exception ex) {
            Logger.getLogger(Recetas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtFiltroProductoKeyReleased

    private void btnSeleccionarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarProductoActionPerformed
        LimpiarTabla(tblPreparacion, modeloPreparaciones);
        int fila = tblBuscarProductos.getSelectedRow();
        try {
            if (fila >= 0) {
                int idProducto = Integer.parseInt(tblBuscarProductos.getValueAt(fila, 0).toString());
                PreparacionDAO pdao = new PreparacionDAO();

                if (pdao.Listar(idProducto).size() > 0) {
                    //cargar tabla de preparacion
                    txtBebida.setText(tblBuscarProductos.getValueAt(fila, 1).toString());
                    lblCodProducto.setText(tblBuscarProductos.getValueAt(fila, 0).toString());
                    cargarPreparacion(idProducto);
                    btnPreparar.setText("MODIFICAR");
                    btnPreparar.setBackground(Color.ORANGE);
                    panelProductos.dispose();
                } else {
                    LimpiarTabla(tblPreparacion, modeloPreparaciones);
                    txtBebida.setText(tblBuscarProductos.getValueAt(fila, 1).toString());
                    lblCodProducto.setText(tblBuscarProductos.getValueAt(fila, 0).toString());
                    btnPreparar.setText("GUARDAR RECETA");
                    btnPreparar.setBackground(new Color(0, 153, 0));
                    panelProductos.dispose();
                }

            } else {
                JOptionPane.showMessageDialog(getRootPane(), "SELECCIONE UN PRODUCTO");
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btnSeleccionarProductoActionPerformed

    private void tblBuscarProductoPresentacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBuscarProductoPresentacionMouseClicked
        if (evt.getClickCount() == 2) {
            btnSeleccionarProductoPresentacion.doClick();
        }
    }//GEN-LAST:event_tblBuscarProductoPresentacionMouseClicked

    private void txtFiltroProductoPresentacionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFiltroProductoPresentacionKeyReleased
        try {
            LlenarTablaBuscarProductoPresentacion(txtFiltroProductoPresentacion.getText());
        } catch (Exception ex) {
            Logger.getLogger(Recetas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtFiltroProductoPresentacionKeyReleased

    private void btnSeleccionarProductoPresentacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarProductoPresentacionActionPerformed
        int fila = tblBuscarProductoPresentacion.getSelectedRow();
        try {
            if (fila >= 0) {
                txtComponente.setText(tblBuscarProductoPresentacion.getValueAt(fila, 1).toString());
                lblProductoPresentacion.setText(tblBuscarProductoPresentacion.getValueAt(fila, 0).toString());
                panelProductoPresentacion.dispose();
            } else {
                JOptionPane.showMessageDialog(getRootPane(), "SELECCIONE UN PRODUCTO");
            }

        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btnSeleccionarProductoPresentacionActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        try {
            VistaRequerimientoBarman vrb = new VistaRequerimientoBarman(usuario, lblAlmacen.getText());
            vrb.setVisible(true);            
            dispose();
        } catch (Exception ex) {
            Logger.getLogger(Recetas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Recetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Recetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Recetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Recetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Recetas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAgregar;
    public javax.swing.JButton btnBuscar;
    public javax.swing.JButton btnPreparar;
    public javax.swing.JButton btnProductoBase;
    public javax.swing.JButton btnQuitar;
    public javax.swing.JButton btnSeleccionarProducto;
    public javax.swing.JButton btnSeleccionarProductoPresentacion;
    public javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblAlmacen;
    private javax.swing.JLabel lblCodProducto;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblProductoPresentacion;
    private javax.swing.JLabel lblUsuario;
    public javax.swing.JDialog panelProductoPresentacion;
    public javax.swing.JDialog panelProductos;
    public javax.swing.JTable tblBuscarProductoPresentacion;
    public javax.swing.JTable tblBuscarProductos;
    public javax.swing.JTable tblPreparacion;
    public javax.swing.JTextField txtBebida;
    public javax.swing.JTextField txtCantidad;
    public javax.swing.JTextField txtComponente;
    public javax.swing.JTextField txtFiltroProducto;
    public javax.swing.JTextField txtFiltroProductoPresentacion;
    private javax.swing.JTextField txtHora;
    // End of variables declaration//GEN-END:variables

    public void titulosBuscarProductos() {
        String titulos[] = {"ID", "PRODUCTO"};
        modeloBuscarProductos = new DefaultTableModel(null, titulos);
        tblBuscarProductos.setModel(modeloBuscarProductos);
    }

    public void titulosBuscarComponentes() {
        String titulos[] = {"ID", "PRODUCTO", "PRESENTACION"};
        modeloBuscarProductoPresentacion = new DefaultTableModel(null, titulos);
        tblBuscarProductoPresentacion.setModel(modeloBuscarProductoPresentacion);
    }

    public void titulosPreparaciones() {
        String titulos[] = {"COD", "NOMBRE", "MEDIDA ML"};
        modeloPreparaciones = new DefaultTableModel(null, titulos);
        tblPreparacion.setModel(modeloPreparaciones);
    }

    public void LlenarTablaBuscarProductos(String nomProd) throws Exception {
        titulosBuscarProductos();
        LimpiarTabla(tblBuscarProductos, modeloBuscarProductos);
        Conexion con = new Conexion();
        try {
            con.conectar();
            String sql = null;
            if (nomProd.equals("")) {
                sql = "select p.idproducto, p.nombre from producto p\n"
                        + "INNER JOIN productopresentacion pp on p.idproducto = pp.idproducto\n"
                        + "WHERE (pp.idcategoria = 1 OR pp.idcategoria = 2) AND pp.idalmacen = 1";
            } else {
                sql = "select p.idproducto, p.nombre from producto p\n"
                        + "INNER JOIN productopresentacion pp on p.idproducto = pp.idproducto\n"
                        + "WHERE ((pp.idcategoria = 1 OR pp.idcategoria = 2) AND pp.idalmacen = 1) AND p.nombre LIKE '%" + nomProd + "%'";
            }

            Object[] datos = new Object[2];
            PreparedStatement pst = con.getConexion().prepareStatement(sql);
            ResultSet res = pst.executeQuery();

            while (res.next()) {
                datos[0] = res.getInt(1);
                datos[1] = res.getString(2);

                modeloBuscarProductos.addRow(datos);
            }

            tblBuscarProductos.setModel(modeloBuscarProductos);
            new ColumnasTablas().dosColumnas(tblBuscarProductos, 50, 200);

            pst.close();
            res.close();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        } finally {
            con.cerrar();
        }
    }

    private void cargarPreparacion(int idProducto) throws SQLException {
        Conexion con = new Conexion();
        try {
            con.conectar();
            String sql = "SELECT productopresentacion.idproductopresentacion, producto.nombre, preparacion.cantidad FROM preparacion\n"
                    + "INNER JOIN productopresentacion ON preparacion.idproductopresentacion = productopresentacion.idproductopresentacion\n"
                    + "INNER JOIN producto ON productopresentacion.idproducto = producto.idproducto\n"
                    + "WHERE preparacion.idproducto = " + idProducto;

            PreparedStatement pst = con.getConexion().prepareStatement(sql);
            ResultSet res = pst.executeQuery();
            Object datos[] = new Object[3];

            while (res.next()) {
                datos[0] = res.getInt(1);
                datos[1] = res.getString(2);
                datos[2] = res.getDouble(3);

                modeloPreparaciones.addRow(datos);
            }

            tblPreparacion.setModel(modeloPreparaciones);

            pst.close();
            res.close();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        } finally {
            con.cerrar();
        }
    }

    public void LlenarTablaBuscarProductoPresentacion(String nomProd) throws Exception {
        titulosBuscarComponentes();
        LimpiarTabla(tblBuscarProductoPresentacion, modeloBuscarProductoPresentacion);
        Conexion con = new Conexion();
        try {
            con.conectar();
            String sql = "select pp.idproductopresentacion, p.nombre, pre.descripcion from producto p\n"
                    + "INNER JOIN productopresentacion pp on p.idproducto = pp.idproducto\n"
                    + "INNER JOIN presentacion pre on pp.idpresentacion = pre.idpresentacion\n"
                    + "WHERE (pp.idcategoria > 2  AND pp.idalmacen = 1) AND p.nombre like '%" + nomProd + "%'";

            Object[] datos = new Object[3];
            PreparedStatement pst = con.getConexion().prepareStatement(sql);
            ResultSet res = pst.executeQuery();

            while (res.next()) {
                datos[0] = res.getInt(1);
                datos[1] = res.getString(2);
                datos[2] = res.getString(3);

                modeloBuscarProductoPresentacion.addRow(datos);
            }

            tblBuscarProductoPresentacion.setModel(modeloBuscarProductoPresentacion);
            new ColumnasTablas().tresColumnas(tblBuscarProductoPresentacion, 50, 200, 100);

            pst.close();
            res.close();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        } finally {
            con.cerrar();
        }
    }

//    public boolean validarProducto(String nomProd) {
//        try {
//            int producto = new ProductoDAO().getIdProducto(nomProd);
//            if (producto > 0) {
//                return true;
//            }
//        } catch (Exception e) {
//            System.out.println(e.getMessage());
//        }
//        return false;
//    }
    public int calcularStock(double stockProductoBase, int equivalencia) {
        //equivalencias ejm: 1 botella 750 ml = 6 cuba libre
        return (int) (stockProductoBase * equivalencia);
    }

    private void LimpiarTabla(JTable tabla, DefaultTableModel modelo) {
        for (int i = 0; i < tabla.getRowCount(); i++) {
            modelo.removeRow(i);
            i -= 1;
        }
    }

}
